// Generated by CoffeeScript 1.3.1
(function() {

  if (!this.cpu_Coordinate || !this.cpu_Collector) {
    return;
  }

  this.cpu_Collector.init();

  this.cpu_Coordinate.init();

  setInterval(function() {
    return this.cpu_Coordinate.draw_data(this.cpu_Collector.data);
  }, 100);

}).call(this);
