// Generated by CoffeeScript 1.3.1
(function() {
  var DATA_SIZE_LIMIT, add_100, add_percent, cal_cpu, d, data, init, step;

  DATA_SIZE_LIMIT = 10000;

  if (this.g_cpu_history) {
    return;
  }

  data = [];

  step = 50;

  d = null;

  cal_cpu = function() {
    var d2, diff;
    d2 = new Date();
    diff = d2 - d - step;
    add_100(Math.floor(diff / step));
    add_percent(Math.floor(diff % step / step * 100));
    return init();
  };

  add_100 = function(count) {
    var _results;
    _results = [];
    while (count-- > 0) {
      _results.push(add_percent(100));
    }
    return _results;
  };

  add_percent = function(percent) {
    if (data.length > DATA_SIZE_LIMIT) {
      return;
    }
    return data.push(percent);
  };

  init = function() {
    d = new Date();
    return setTimeout(cal_cpu, step);
  };

  this.g_cpu_history = {
    init: init,
    data: data
  };

}).call(this);
